##### Write a Python program that takes a 3D point as an input and calculates its Euclidean norm and Mahalanobis norm from the center of the two clusters of data given in the attachment. Visualize the clusters and the input data point in a 3D plot.

In [50]:
import pandas as pd
import math
import numpy as np

In [84]:
df1 = pd.read_csv('3D_cluster1.csv')
df1 = df1.to_numpy()
df1

array([[ 3.35298026, 20.2771002 , 13.8754487 ],
       [11.24464507, 21.89848195, 15.16543545],
       [ 5.76887738, 19.36887766, 14.34909674],
       [18.54011395, 19.84338744, 15.92822873],
       [12.63685455, 20.34697112, 15.54954282],
       [10.5146924 , 20.9452895 , 14.52320382],
       [13.5193979 , 20.33746107, 14.17870926],
       [29.29671811, 19.02183674, 14.4933235 ],
       [15.40572584, 21.16089919, 15.35128616],
       [ 2.36428248, 19.84676453, 15.9963063 ],
       [13.13026386, 19.69774217, 15.56320067],
       [11.52323604, 20.01044249, 14.72223527],
       [32.89273026, 18.9691162 , 15.21274112],
       [ 9.62492399, 20.18528098, 14.51822777],
       [11.65481477, 20.29447513, 15.14381458],
       [31.99174789, 21.77642433, 13.70611905],
       [ 4.4091439 , 21.50727593, 16.06434092],
       [19.52143066, 19.17943343, 16.44368617],
       [17.38226614, 19.81834411, 15.62928663],
       [ 4.71617808, 20.72918632, 14.69093662],
       [ 9.01166248, 19.86752198, 16.900

In [85]:
df2 = pd.read_csv('3D_cluster2.csv')
df2 = df2.to_numpy()
df2

array([[18.81851518, 16.32546815, 30.8572121 ],
       [21.39526023, 21.97262064, 21.09809828],
       [24.90632763, 26.93336193, 23.21301099],
       [19.55532426, 19.13115931, 11.94918615],
       [25.38960764, 25.7119417 , 14.60989507],
       [28.58158246, 28.99773409, 17.78030686],
       [23.94699162, 24.62216759, 23.67775376],
       [24.96349351, 20.26201292, 20.80647178],
       [34.87340622, 20.1795708 , 23.61778061],
       [21.80698686, 21.32982265, 23.87460975],
       [27.1504882 , 21.8069437 , 22.7271618 ],
       [21.12204439, 23.1474254 , 27.81869127],
       [25.17319482, 20.20399209, 26.39542324],
       [30.72486729, 24.86321645, 19.74571645],
       [22.93501927, 21.78855624, 17.07509655],
       [21.15193067, 33.40382576, 20.98980146],
       [29.38757353, 27.34232209, 15.97413465],
       [32.01679139, 18.36178011, 19.817789  ],
       [30.39208359, 17.59084171, 22.69572893],
       [18.0499148 , 25.63336323, 20.24374476],
       [31.5073685 , 17.11307337, 17.183

In [86]:
center1= np.mean(df1,axis=0)
center1

array([14.29567941, 19.89971   , 14.88743356])

In [87]:
center2= np.mean(df2,axis=0)
center2

array([24.36679023, 20.81699166, 19.67764138])

In [88]:
cov1 =np.cov(df1, rowvar=False)
cov1

array([[ 9.00708840e+01, -7.08734326e-01,  1.38232206e-01],
       [-7.08734326e-01,  1.08315591e+00, -4.84640089e-02],
       [ 1.38232206e-01, -4.84640089e-02,  8.74028311e-01]])

In [89]:
cov2 = np.cov(df2, rowvar=False)
cov2


array([[27.32255588,  2.74651915,  1.58742997],
       [ 2.74651915, 22.16926548, -2.85286442],
       [ 1.58742997, -2.85286442, 18.93493102]])

In [90]:
def euclidean_norm(point, center):
    x1, x2= point[0],center[0]
    y1, y2= point[1],center[1]
    z1, z2= point[2],center[2]
    distance = math.sqrt((x1-x2)**2 + (y1-y2)**2 + (z1-z2)**2)
    return distance

In [91]:
def mahalanobis_norm(point, center, cov_matrix):
    diff = point - center
    inv_cov_matrix = np.linalg.inv(cov_matrix)
    return np.sqrt(np.dot(np.dot(diff.T, inv_cov_matrix), diff))
    
    

In [92]:
x =float(input("Enter x Coordinate: "))
y =float(input("Enter y Coordinate: "))
z =float(input("Enter x Coordinate: "))
point =np.array([x,y,z])

In [93]:
euclidean_norm1 = euclidean_norm(point, center1)
euclidean_norm2 = euclidean_norm(point, center2)


In [94]:
mahalanobis_norm1 = mahalanobis_norm(point, center1, cov1)
mahalanobis_norm2 = mahalanobis_norm(point, center2, cov2)

In [95]:

print(f"Euclidean Norm from Center of Cluster 1: {euclidean_norm1}")
print(f"Euclidean Norm from Center of Cluster 2: {euclidean_norm2}")
print(f"Mahalanobis Norm from Center of Cluster 1: {mahalanobis_norm1}")
print(f"Mahalanobis Norm from Center of Cluster 2: {mahalanobis_norm2}")


Euclidean Norm from Center of Cluster 1: 24.39131098259556
Euclidean Norm from Center of Cluster 2: 33.39938947661772
Mahalanobis Norm from Center of Cluster 1: 20.81112378120023
Mahalanobis Norm from Center of Cluster 2: 6.749315967987916
